name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx vsce package --out vscode-splunk-soar.vsix
      - uses: actions/upload-artifact@v3
        with:
          name: vscode-splunk-soar.vsix
          path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: vscode-splunk-soar.vsix
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npx vsce publish --packagePath $(find . -type f -iname '*.vsix')
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
